<a href="https://colab.research.google.com/github/riajahmed19/Js/blob/master/DM_labReport3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules, fpgrowth

In [ ]:
data = pd.read_csv("/content/Market_Basket_Optimisation.csv")

transactions = data.values.tolist()
toArray=[]
for i in range(len(transactions)):
  array=[]
  for j in range(len(transactions[i])):
    if(str(transactions[i][j])!='nan'):
      array.append(str(transactions[i][j]))
  toArray.append(array)

transactions=toArray
transactions

[['burgers', 'meatballs', 'eggs'],
 ['chutney'],
 ['turkey', 'avocado'],
 ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea'],
 ['low fat yogurt'],
 ['whole wheat pasta', 'french fries'],
 ['soup', 'light cream', 'shallot'],
 ['frozen vegetables', 'spaghetti', 'green tea'],
 ['french fries'],
 ['eggs', 'pet food'],
 ['cookies'],
 ['turkey', 'burgers', 'mineral water', 'eggs', 'cooking oil'],
 ['spaghetti', 'champagne', 'cookies'],
 ['mineral water', 'salmon'],
 ['mineral water'],
 ['shrimp',
  'chocolate',
  'chicken',
  'honey',
  'oil',
  'cooking oil',
  'low fat yogurt'],
 ['turkey', 'eggs'],
 ['turkey',
  'fresh tuna',
  'tomatoes',
  'spaghetti',
  'mineral water',
  'black tea',
  'salmon',
  'eggs',
  'chicken',
  'extra dark chocolate'],
 ['meatballs', 'milk', 'honey', 'french fries', 'protein bar'],
 ['red wine', 'shrimp', 'pasta', 'pepper', 'eggs', 'chocolate', 'shampoo'],
 ['rice', 'sparkling water'],
 ['spaghetti', 'mineral water', 'ham', 'body spray', 'pancakes', 'green tea'],
 ['burgers',
  'grated cheese',
  'shrimp',
  'pasta',
  'avocado',
  'honey',
  'white wine',
  'toothpaste'],
 ['eggs'],
 ['parmesan cheese', 'spaghetti', 'soup', 'avocado', 'milk', 'fresh bread'],
 ['ground beef',
  'spaghetti',
  'mineral water',
  'milk',
  'energy bar',
  'black tea',
  'salmon',
  'frozen smoothie',
  'escalope'],
 ['sparkling water'],
 ['mineral water', 'eggs', 'chicken', 'chocolate', 'french fries'],
 ['frozen vegetables', 'spaghetti', 'yams', 'mineral water'],
 ['herb & pepper', 'tomato sauce', 'light cream', 'magazines'],
 ['mineral water', 'chocolate', 'avocado', 'eggs'],
 ['turkey', 'french fries', 'strawberries'],
 ['frozen vegetables', 'strong cheese', 'chocolate'],
 ['cookies'],
 ['pickles', 'spaghetti', 'salmon', 'escalope'],
 ['energy bar', 'french fries'],
 ['red wine', 'ground beef', 'mineral water'],
 ['mineral water', 'cake', 'cottage cheese'],
 ['pickles', 'champagne', 'green tea'],
 ['spaghetti'],
 ['fresh tuna',
  'frozen vegetables',
  'spaghetti',
  'mineral water',
  'honey',
  'whole wheat rice',
  'frozen smoothie',
  'escalope'],
 ['spaghetti'],
 ['soup', 'meatballs', 'hot dogs', 'sparkling water'],
 ['escalope'],
 ['soup',
  'avocado',
  'french fries',
  'hot dogs',
  'brownies',
  'body spray',
  'pancakes',
  'green tea'],
 ['mineral water', 'chicken', 'cereals', 'clothes accessories'],
 ['mineral water', 'bug spray'],
 ['avocado', 'muffins'],
 ['burgers', 'black tea', 'green tea'],
 ['spaghetti', 'chocolate', 'brownies', 'white wine', 'green tea'],
 ['fresh tuna', 'mineral water', 'eggs'],
 ['spaghetti', 'muffins'],
 ['spaghetti', 'chocolate'],
 ['french fries', 'escalope', 'champagne'],
 ['tomato sauce', 'light mayo'],
 ['turkey',
  'fresh tuna',
  'frozen vegetables',
  'tomatoes',
  'ground beef',
  'spaghetti',
  'mineral water',
  'chocolate',
  'soup',
  'milk',
  'olive oil'],
 ['eggs', 'cookies'],
 ['soup',
  'chicken',
  'gums',
  'soda',
  'body spray',
  'energy drink',
  'green tea'],
 ['turkey',
  'frozen vegetables',
  'mineral water',
  'cider',
  'cooking oil',
  'green tea'],
 ['spaghetti'],
 ['clothes accessories'],
 ['energy drink'],
 ['soup', 'bug spray', 'shallot', 'protein bar', 'green tea'],
 ['turkey', 'eggs'],
 ['french fries'],
 ['chocolate', 'milk'],
 ['herb & pepper',
  'whole wheat pasta',
  'ground beef',
  'mineral water',
  'avocado',
  'cider',
  'whole wheat rice'],
 ['cookies'],
 ['shrimp', 'pasta'],
 ['grated cheese', 'herb & pepper', 'tomatoes', 'tomato sauce', 'corn'],
 ['burgers', 'escalope', 'shallot'],
 ['cookies'],
 ['yogurt cake'],
 ['soup', 'eggs'],
 ['cookies'],
 ['mineral water', 'chocolate', 'low fat yogurt'],
 ['eggs', 'strawberries'],
 ['grated cheese', 'ground beef', 'spaghetti', 'mineral water', 'white wine'],
 ['mint'],
 ['eggs', 'cake', 'french fries'],
 ['burgers', 'spaghetti', 'milk', 'french fries', 'green tea'],
 ['mineral water', 'energy bar', 'butter', 'french fries'],
 ['burgers',
  'grated cheese',
  'herb & pepper',
  'mineral water',
  'eggs',
  'cooking oil'],
 ['energy bar'],
 ['energy bar', 'energy drink'],
 ['chocolate', 'frozen smoothie'],
 ['low fat yogurt'],
 ['asparagus', 'salad'],
 ['burgers', 'french fries', 'low fat yogurt', 'green tea'],
 ['low fat yogurt'],
 ['burgers',
  'herb & pepper',
  'shrimp',
  'pasta',
  'spaghetti',
  'mineral water',
  'meatballs',
  'olive oil',
  'energy bar',
  'french wine',
  'eggs',
  'salt'],
 ['champagne', 'low fat yogurt'],
 ['champagne'],
 ['burgers', 'almonds', 'eggs', 'french fries', 'cookies', 'green tea'],
 ['ham', 'soup', 'escalope', 'body spray'],
 ['turkey',
  'ham',
  'frozen vegetables',
  'pepper',
  'oil',
  'extra dark chocolate',
  'tea',
  'magazines'],
 ['muffins', 'eggs', 'cookies'],
 ['cookies'],
 ['frozen vegetables',
  'whole wheat pasta',
  'ground beef',
  'spaghetti',
  'chocolate',
  'green tea'],
 ['mineral water', 'barbecue sauce', 'chocolate'],
 ['burgers',
  'herb & pepper',
  'energy bar',
  'almonds',
  'eggs',
  'corn',
  'mayonnaise',
  'zucchini'],
 ['turkey',
  'burgers',
  'ground beef',
  'chocolate',
  'soup',
  'almonds',
  'eggs',
  'hot dogs',
  'cottage cheese'],
 ['ham', 'spaghetti', 'chocolate', 'eggs'],
 ['ground beef', 'energy bar', 'pet food', 'carrots', 'protein bar'],
 ['ground beef',
  'tomato sauce',
  'spaghetti',
  'mineral water',
  'almonds',
  'eggs'],
 ['mineral water', 'olive oil', 'gums', 'cooking oil'],
 ['shrimp',
  'pasta',
  'mineral water',
  'soup',
  'avocado',
  'milk',
  'olive oil',
  'green grapes',
  'eggs',
  'bug spray'],
 ['shrimp',
  'pasta',
  'soup',
  'cake',
  'cooking oil',
  'chicken',
  'light mayo',
  'low fat yogurt'],
 ['spaghetti',
  'mineral water',
  'chocolate',
  'french fries',
  'champagne',
  'escalope',
  'mushroom cream sauce',
  'fresh bread'],
 ['shrimp', 'pasta', 'mineral water', 'eggs'],
 ['burgers', 'oil', 'tomato juice', 'fresh bread'],
 ['french wine', 'eggs', 'chocolate', 'low fat yogurt'],
 ['chicken', 'eggs', 'french fries', 'pancakes'],
 ['turkey', 'herb & pepper', 'salmon', 'white wine', 'candy bars'],
 ['grated cheese',
  'spaghetti',
  'olive oil',
  'eggs',
  'french fries',
  'green tea'],
 ['mineral water', 'energy bar'],
 ['eggs', 'french fries'],
 ['burgers',
  'tomatoes',
  'mineral water',
  'soup',
  'milk',
  'almonds',
  'eggs',
  'chocolate',
  'tomato juice'],
 ['muffins'],
 ['pasta'],
 ['tomatoes', 'spaghetti', 'frozen smoothie'],
 ['ground beef', 'spaghetti', 'milk'],
 ['french fries'],
 ['chocolate', 'milk'],
 ['burgers',
  'shrimp',
  'pasta',
  'frozen vegetables',
  'spaghetti',
  'mineral water',
  'milk',
  'eggs',
  'chocolate',
  'french fries',
  'pancakes',
  'low fat yogurt'],
 ['ground beef', 'mineral water', 'antioxydant juice', 'protein bar'],
 ['grated cheese',
  'whole wheat pasta',
  'ground beef',
  'spaghetti',
  'cake',
  'energy drink'],
 ['grated cheese'],
 ['pancakes'],
 ['frozen smoothie'],
 ['carrots', 'green tea'],
 ['chocolate'],
 ['turkey',
  'burgers',
  'chocolate',
  'olive oil',
  'eggs',
  'cooking oil',
  'corn'],
 ['frozen vegetables',
  'tomatoes',
  'pepper',
  'spaghetti',
  'mineral water',
  'pancakes',
  'chicken',
  'chili',
  'tea',
  'french fries',
  'tomato juice',
  'fresh bread'],
 ['cookies'],
 ['ground beef'],
 ['turkey', 'eggs', 'chocolate', 'frozen smoothie', 'tomato juice'],
 ['frozen vegetables', 'cooking oil', 'mashed potato'],
 ['frozen vegetables',
  'ground beef',
  'tomato sauce',
  'mineral water',
  'meatballs',
  'olive oil',
  'light cream',
  'tomato juice'],
 ['red wine',
  'spaghetti',
  'mineral water',
  'soup',
  'milk',
  'eggs',
  'cake',
  'gums',
  'cooking oil',
  'chocolate',
  'frozen smoothie'],
 ['chocolate',
  'tomatoes',
  'spaghetti',
  'mineral water',
  'avocado',
  'milk',
  'olive oil',
  'eggs',
  'rice',
  'french fries',
  'brownies'],
 ['chocolate',
  'shrimp',
  'pasta',
  'frozen vegetables',
  'ground beef',
  'mineral water',
  'nonfat milk',
  'eggs'],
 ['turkey',
  'shrimp',
  'pasta',
  'pepper',
  'spaghetti',
  'mineral water',
  'eggs',
  'chicken',
  'french fries'],
 ['cookies'],
 ['turkey', 'tomatoes', 'cake'],
 ['yams',
  'mineral water',
  'soup',
  'milk',
  'pancakes',
  'whole wheat rice',
  'barbecue sauce',
  'carrots',
  'chocolate',
  'champagne'],
 ['rice'],
 ['chocolate', 'milk'],
 ['shrimp', 'pasta', 'frozen vegetables', 'water spray'],
 ['burgers', 'mineral water', 'milk', 'eggs', 'whole wheat rice', 'mint'],
 ['mineral water', 'vegetables mix', 'cake', 'frozen smoothie', 'brownies'],
 ['cookies'],
 ['shrimp', 'pasta', 'chicken', 'chocolate bread'],
 ['shallot'],
 ['shrimp', 'pasta', 'spaghetti', 'eggs', 'hot dogs', 'green tea'],
 ['burgers'],
 ['red wine',
  'ground beef',
  'spaghetti',
  'mineral water',
  'milk',
  'olive oil',
  'strong cheese',
  'light cream',
  'cooking oil'],
 ['burgers',
  'grated cheese',
  'spaghetti',
  'avocado',
  'milk',
  'oil',
  'french fries'],
 ['herb & pepper',
  'whole wheat pasta',
  'ground beef',
  'mineral water',
  'olive oil'],
 ['shrimp', 'pasta', 'yams', 'milk', 'chocolate'],
 ['butter', 'green tea'],
 ['light mayo'],
 ['low fat yogurt'],
 ['herb & pepper', 'shrimp', 'pasta', 'spaghetti', 'milk'],
 ['burgers', 'eggs'],
 ['turkey',
  'herb & pepper',
  'ground beef',
  'soup',
  'avocado',
  'milk',
  'black tea',
  'eggs',
  'barbecue sauce',
  'carrots',
  'cookies',
  'tomato juice',
  'fresh bread'],
 ['cookies'],
 ['escalope'],
 ['pepper', 'french fries', 'strawberries', 'pancakes', 'low fat yogurt'],
 ['frozen vegetables', 'yams', 'chicken', 'honey', 'light mayo'],
 ['chocolate', 'champagne'],
 ['herb & pepper', 'honey', 'cake', 'rice', 'protein bar'],
 ['burgers',
  'chocolate',
  'frozen vegetables',
  'ground beef',
  'mineral water',
  'milk',
  'light mayo',
  'asparagus'],
 ['chocolate', 'mineral water', 'corn', 'cottage cheese', 'green tea'],
 ['muffins'],
 ['ham', 'french wine', 'escalope'],
 ['spaghetti', 'milk', 'whole wheat rice', 'mint green tea'],
 ['chocolate', 'body spray'],
 ['frozen vegetables', 'french fries', 'hot dogs'],
 ['candy bars'],
 ['burgers',
  'shrimp',
  'pasta',
  'milk',
  'green tea',
  'french fries',
  'cookies',
  'white wine'],
 ['parmesan cheese', 'ground beef'],
 ['pancakes', 'whole wheat rice', 'candy bars'],
 ['eggs', 'eggplant', 'cookies'],
 ['frozen vegetables', 'mineral water'],
 ['chocolate'],
 ['turkey', 'spaghetti', 'milk', 'whole wheat rice', 'chocolate'],
 ['whole wheat pasta',
  'ground beef',
  'spaghetti',
  'soup',
  'meatballs',
  'chicken',
  'blueberries',
  'cooking oil',
  'champagne',
  'yogurt cake',
  'protein bar'],
 ['cooking oil', 'tomato juice'],
 ['frozen vegetables', 'milk', 'eggs', 'french fries', 'green tea'],
 ['fresh tuna',
  'spaghetti',
  'olive oil',
  'french wine',
  'eggs',
  'french fries',
  'champagne',
  'pancakes',
  'light mayo'],
 ['red wine', 'honey', 'hot dogs'],
 ['milk', 'bacon', 'eggs', 'french fries', 'fresh bread'],
 ['french fries', 'yogurt cake'],
 ['milk'],
 ['french fries'],
 ['chocolate'],
 ['burgers', 'ham', 'red wine'],
 ['shrimp',
  'pasta',
  'tomatoes',
  'energy bar',
  'french wine',
  'antioxydant juice',
  'french fries',
  'frozen smoothie',
  'brownies'],
 ['green tea'],
 ['low fat yogurt'],
 ['turkey',
  'spaghetti',
  'mineral water',
  'soup',
  'spinach',
  'soda',
  'energy drink',
  'salt'],
 ['turkey', 'eggs'],
 ['bug spray', 'hot dogs'],
 ['oil'],
 ['soup',
  'energy bar',
  'chicken',
  'eggs',
  'cake',
  'french fries',
  'body spray',
  'strawberries'],
 ['spaghetti', 'chocolate', 'yogurt cake'],
 ['turkey', 'mineral water', 'meatballs'],
 ['ground beef',
  'mineral water',
  'chocolate',
  'fromage blanc',
  'bacon',
  'hot dogs'],
 ['frozen vegetables', 'mineral water', 'vegetables mix', 'escalope'],
 ['herb & pepper', 'red wine', 'tomatoes'],
 ['whole wheat pasta', 'olive oil', 'cereals', 'brownies', 'green tea'],
 ['cookies'],
 ['olive oil', 'cookies', 'mushroom cream sauce'],
 ['ground beef', 'pancakes', 'cooking oil', 'gluten free bar', 'light mayo'],
 ['mineral water', 'french fries'],
 ['herb & pepper'],
 ['salmon'],
 ['eggs', 'escalope'],
 ['mineral water', 'tomato juice'],
 ['mineral water'],
 ['shrimp', 'mineral water', 'soup', 'black tea'],
 ['cake', 'frozen smoothie'],
 ['turkey',
  'burgers',
  'grated cheese',
  'tomatoes',
  'chocolate',
  'fromage blanc',
  'honey',
  'whole wheat rice'],
 ['frozen vegetables',
  'ground beef',
  'mineral water',
  'olive oil',
  'pancakes'],
 ['turkey',
  'burgers',
  'ground beef',
  'milk',
  'olive oil',
  'cake',
  'fresh bread'],
 ['whole wheat pasta',
  'ground beef',
  'spaghetti',
  'yams',
  'mineral water',
  'soup',
  'chutney',
  'cereals',
  'energy drink',
  'protein bar'],
 ['eggs', 'whole wheat rice', 'cake', 'green tea', 'escalope'],
 ['ground beef', 'yams', 'soup', 'avocado', 'salmon', 'green tea'],
 ['milk'],
 ['spaghetti', 'chocolate'],
 ['whole wheat pasta', 'honey'],
 ['whole wheat pasta', 'green tea'],
 ['spaghetti', 'meatballs', 'vegetables mix', 'chocolate'],
 ['eggs', 'low fat yogurt'],
 ['fresh tuna',
  'shrimp',
  'pasta',
  'mineral water',
  'olive oil',
  'eggs',
  'cake',
  'brownies',
  'tomato juice'],
 ['mineral water', 'green grapes', 'hot dogs', 'fresh bread'],
 ['frozen vegetables', 'meatballs', 'eggs', 'chocolate'],
 ['chocolate'],
 ['meatballs', 'milk'],
 ['low fat yogurt'],
 ['green tea'],
 ['escalope', 'pasta'],
 ['pepper',
  'chocolate',
  'olive oil',
  'french wine',
  'salmon',
  'rice',
  'light mayo',
  'fresh bread',
  'magazines'],
 ['red wine',
  'french wine',
  'vegetables mix',
  'rice',
  'clothes accessories',
  'hot dogs',
  'green tea'],
 ['burgers',
  'dessert wine',
  'spaghetti',
  'chicken',
  'cake',
  'protein bar',
  'green tea'],
 ['french wine', 'cake', 'fresh bread'],
 ['burgers', 'frozen vegetables', 'flax seed', 'eggs'],
 ['red wine'],
 ['pepper', 'mineral water', 'energy bar', 'green grapes'],
 ['milk', 'eggs', 'cake', 'chocolate', 'french fries', 'green tea'],
 ['french fries'],
 ['almonds'],
 ['burgers', 'mineral water', 'green tea'],
 ['milk', 'pancakes'],
 ['pancakes', 'eggs', 'salt', 'tomato juice'],
 ['mineral water'],
 ['ham', 'spaghetti', 'mineral water', 'olive oil'],
 ['salt', 'tomato juice', 'fresh bread'],
 ['spaghetti', 'mushroom cream sauce'],
 ['spaghetti', 'mineral water', 'eggs', 'pet food'],
 ['frozen vegetables', 'spaghetti'],
 ['energy drink'],
 ['muffins'],
 ['turkey', 'milk'],
 ['cookies'],
 ['chocolate'],
 ['spaghetti',
  'mineral water',
  'eggs',
  'cooking oil',
  'chocolate',
  'escalope'],
 ['shrimp', 'frozen vegetables', 'pepper', 'spaghetti', 'green tea'],
 ['burgers',
  'fresh tuna',
  'red wine',
  'mineral water',
  'french fries',
  'hand protein bar',
  'low fat yogurt'],
 ['pancakes', 'eggs', 'energy drink', 'fresh bread'],
 ['strong cheese',
  'salmon',
  'green tea',
  'french fries',
  'frozen smoothie',
  'hot dogs'],
 ['grated cheese',
  'shrimp',
  'pasta',
  'tomatoes',
  'milk',
  'frozen smoothie',
  'sandwich'],
 ['herb & pepper', 'whole wheat pasta', 'olive oil', 'pancakes', 'eggs'],
 ['spaghetti', 'antioxydant juice'],
 ['chocolate', 'milk', 'almonds', 'eggs', 'strawberries', 'white wine'],
 ['french fries', 'strawberries'],
 ['mineral water'],
 ['eggs'],
 ['escalope'],
 ['cake'],
 ['whole wheat pasta', 'antioxydant juice', 'body spray', 'green tea'],
 ['mineral water', 'oil', 'frozen smoothie'],
 ['french fries', 'champagne'],
 ['chocolate', 'french fries'],
 ['frozen vegetables', 'spaghetti', 'eggs'],
 ['hot dogs'],
 ['chocolate', 'cookies'],
 ['pancakes'],
 ['shrimp', 'butter', 'chicken', 'salmon'],
 ['chocolate', 'cookies', 'babies food'],
 ['pepper', 'spaghetti', 'cake', 'chocolate', 'french fries', 'fresh bread'],
 ['avocado', 'oil', 'cereals', 'french fries'],
 ['herb & pepper',
  'spaghetti',
  'mineral water',
  'spinach',
  'eggs',
  'oil',
  'cooking oil',
  'green tea',
  'shampoo',
  'tomato juice',
  'low fat yogurt'],
 ['herb & pepper',
  'frozen vegetables',
  'ground beef',
  'pepper',
  'spaghetti',
  'mint green tea',
  'french fries'],
 ['french fries'],
 ['green tea', 'tomato juice'],
 ['eggs', 'whole wheat rice', 'chocolate'],
 ['grated cheese',
  'herb & pepper',
  'red wine',
  'spaghetti',
  'mineral water',
  'salmon',
  'eggs',
  'cooking oil',
  'green tea'],
 ['french fries',
  'cookies',
  'shallot',
  'tomato juice',
  'fresh bread',
  'low fat yogurt'],
 ['burgers', 'fresh tuna', 'spaghetti', 'muffins', 'honey'],
 ['herb & pepper', 'ground beef', 'spaghetti', 'eggs', 'chicken'],
 ['grated cheese', 'muffins', 'tomato juice', 'mayonnaise'],
 ['whole wheat pasta',
  'yams',
  'mineral water',
  'muffins',
  'frozen smoothie',
  'hot dogs',
  'energy drink'],
 ['burgers',
  'spaghetti',
  'soup',
  'milk',
  'olive oil',
  'salmon',
  'eggs',
  'blueberries'],
 ['chocolate', 'champagne', 'magazines'],
 ['frozen vegetables',
  'spaghetti',
  'yams',
  'mineral water',
  'french wine',
  'green grapes',
  'rice',
  'chocolate'],
 ['tomato sauce', 'chocolate'],
 ['milk', 'eggs'],
 ['pet food'],
 ['yogurt cake'],
 ['green tea'],
 ['escalope', 'pasta'],
 ['herb & pepper', 'ground beef'],
 ['mineral water', 'honey', 'brownies'],
 ['turkey', 'eggs', 'cake', 'energy drink'],
 ['turkey',
  'burgers',
  'dessert wine',
  'ground beef',
  'soup',
  'salmon',
  'eggs',
  'gums',
  'tomato juice',
  'candy bars'],
 ['spaghetti', 'mineral water', 'chicken'],
 ['turkey', 'ground beef', 'carrots', 'french fries', 'melons'],
 ['mineral water', 'eggs', 'low fat yogurt'],
 ['turkey', 'cooking oil', 'shampoo'],
 ['spaghetti', 'hot dogs'],
 ['chocolate', 'green tea'],
 ['grated cheese',
  'pepper',
  'mineral water',
  'chocolate',
  'eggs',
  'cake',
  'mashed potato',
  'tomato juice'],
 ['chocolate'],
 ['spaghetti', 'olive oil', 'strong cheese', 'pancakes'],
 ['red wine', 'mineral water', 'soup', 'rice', 'cookies'],
 ['red wine', 'shrimp', 'spaghetti'],
 ['green tea'],
 ['mineral water', 'chicken', 'french fries', 'frozen smoothie'],
 ['muffins'],
 ['cake', 'chocolate'],
 ['fresh tuna',
  'tomatoes',
  'mineral water',
  'soup',
  'avocado',
  'meatballs',
  'olive oil'],
 ['turkey', 'french fries'],
 ['burgers',
  'turkey',
  'herb & pepper',
  'ground beef',
  'pancakes',
  'eggs',
  'light cream',
  'rice',
  'champagne',
  'fresh bread'],
 ['escalope'],
 ['chocolate', 'escalope', 'fresh bread'],
 ['ham',
  'spaghetti',
  'french wine',
  'vegetables mix',
  'chocolate',
  'french fries'],
 ['avocado', 'light mayo'],
 ['spaghetti', 'yams', 'butter', 'chocolate'],
 ['energy bar', 'eggs', 'french fries'],
 ['fresh tuna', 'barbecue sauce', 'eggplant'],
 ['energy drink'],
 ['whole wheat rice', 'french fries', 'hot dogs', 'green tea'],
 ['mineral water', 'chicken', 'green tea'],
 ['eggs', 'cake', 'mushroom cream sauce'],
 ['escalope'],
 ['antioxydant juice', 'escalope'],
 ['shrimp', 'spaghetti', 'french fries'],
 ['grated cheese', 'spaghetti', 'salmon', 'tomato juice'],
 ['spaghetti', 'green tea'],
 ['champagne', 'protein bar'],
 ['mineral water', 'avocado', 'chocolate'],
 ['tomatoes', 'champagne', 'green tea'],
 ['chicken', 'french fries', 'escalope'],
 ['frozen vegetables',
  'tomatoes',
  'eggs',
  'green tea',
  'frozen smoothie',
  'light mayo'],
 ['ground beef',
  'chicken',
  'cider',
  'green grapes',
  'honey',
  'chocolate',
  'french fries',
  'champagne',
  'frozen smoothie',
  'escalope'],
 ['french fries', 'champagne'],
 ['mineral water', 'soup'],
 ['frozen vegetables', 'spaghetti', 'milk', 'chocolate', 'babies food'],
 ['honey', 'whole wheat rice'],
 ['whole wheat rice', 'chicken', 'tomato juice'],
 ['pancakes'],
 ['green tea', 'protein bar', 'tomato juice', 'candy bars'],
 ['french fries'],
 ['mineral water'],
 ['escalope'],
 ['grated cheese',
  'herb & pepper',
  'whole wheat pasta',
  'yams',
  'mineral water',
  'bacon',
  'nonfat milk',
  'spinach'],
 ['spaghetti', 'milk'],
 ['milk', 'chocolate', 'white wine'],
 ['sandwich'],

In [ ]:
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)

frequent_itemsets = apriori(df, min_support=0.03, use_colnames=True)

rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.3)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(chocolate),(mineral water),0.163867,0.238267,0.052667,0.321400,1.348907,1.0,0.013623,1.122506,0.309351,0.150706,0.109136,0.271220
1,(frozen vegetables),(mineral water),0.095333,0.238267,0.035733,0.374825,1.573133,1.0,0.013019,1.218433,0.402718,0.119964,0.179273,0.262399
2,(ground beef),(mineral water),0.098267,0.238267,0.040933,0.416554,1.748266,1.0,0.017520,1.305576,0.474647,0.138475,0.234054,0.294175
3,(ground beef),(spaghetti),0.098267,0.174133,0.039200,0.398915,2.290857,1.0,0.022088,1.373959,0.624888,0.168096,0.272176,0.312015
4,(milk),(mineral water),0.129600,0.238267,0.048000,0.370370,1.554436,1.0,0.017121,1.209812,0.409789,0.150063,0.173425,0.285913
5,(pancakes),(mineral water),0.095067,0.238267,0.033733,0.354839,1.489250,1.0,0.011082,1.180687,0.363034,0.112595,0.153035,0.248208
6,(spaghetti),(mineral water),0.174133,0.238267,0.059733,0.343032,1.439698,1.0,0.018243,1.159468,0.369806,0.169376,0.137536,0.296866

In [ ]:
frequent_itemsets = fpgrowth(df, min_support=0.03, use_colnames=True)
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.3)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(chocolate),(mineral water),0.163867,0.238267,0.052667,0.321400,1.348907,1.0,0.013623,1.122506,0.309351,0.150706,0.109136,0.271220
1,(frozen vegetables),(mineral water),0.095333,0.238267,0.035733,0.374825,1.573133,1.0,0.013019,1.218433,0.402718,0.119964,0.179273,0.262399
2,(ground beef),(mineral water),0.098267,0.238267,0.040933,0.416554,1.748266,1.0,0.017520,1.305576,0.474647,0.138475,0.234054,0.294175
3,(ground beef),(spaghetti),0.098267,0.174133,0.039200,0.398915,2.290857,1.0,0.022088,1.373959,0.624888,0.168096,0.272176,0.312015
4,(milk),(mineral water),0.129600,0.238267,0.048000,0.370370,1.554436,1.0,0.017121,1.209812,0.409789,0.150063,0.173425,0.285913
5,(pancakes),(mineral water),0.095067,0.238267,0.033733,0.354839,1.489250,1.0,0.011082,1.180687,0.363034,0.112595,0.153035,0.248208
6,(spaghetti),(mineral water),0.174133,0.238267,0.059733,0.343032,1.439698,1.0,0.018243,1.159468,0.369806,0.169376,0.137536,0.296866